repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types:
          - csv
          - svg
          - png
          - webp
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
        exclude: ^chart/templates/

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v2.4.1
  #   hooks:
  #     - id: prettier
  #       additional_dependencies:
  #         - 'prettier@2.4.1'

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.1.0
    hooks:
      - id: eslint
        files: '\.vue'
        types: [file]
        additional_dependencies:
          - 'eslint@8.1.0'
          - 'eslint-config-prettier@8.3.0'
          - 'eslint-plugin-vue@8.0.3'
          - 'eslint-plugin-vuetify@1.1.0'
