language: node_js
# safelist
branches:
  only:
  - master
  - develop
node_js:
  - lts/*
before_script:
  - npm i -g node-gyp
  - npm i
script:
  - npm run test:unit
  - npm run build


jobs:
  include:
    # 👇 Adds Chromatic as a job
    - name: 'Publish to Chromatic'
      script: npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes
