branches:
  only:
  - master
  - develop

jobs:
  include:
    - language: python
      python: 3.10

    - language: node_js
      node_js: lts/*
      before_script:
        - npm i node-gyp -g
        - npm i
      script:
        - npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes
        - npm run test:unit
        - npm run build
