language: node_js

branches:
  only:
  - master
  - develop
node_js:
  - lts/*
before_script:
  - npm i -g node-gyp
  - npm i

jobs:
  include:
    - name: 'Publish to Chromatic'
      script: npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes --exit-once-uploaded
    - name: 'run unit tests'
      script: npm run test:unit
    - name: 'test creating a build'
      script: npm run build
