language: node_js
# safelist
branches:
  only:
  - master
  - develop
node_js:
  - "16.11.1"
before_install:
  - npm i
script:
  - npm run test:unit
  - npm run build


jobs:
  include:
    # 👇 Adds Chromatic as a job
    - name: 'Publish to Chromatic'
      script: npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN}
