branches:
  only:
  - master
  - develop

jobs:
  include:
    - language: python
      python: 3

    - language: node_js
      node_js: lts/*
      before_script:
        - npm i node-gyp -g
        - npm i

    - name: 'Publish to Chromatic'
      script: npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes
    - name: 'run unit tests'
      script: npm run test:unit
    - name: 'test creating a build'
      script: npm run build
