language: node_js

branches:
  only:
  - master
  - develop
node_js:
  - "12"
before_script:
  - npm i

jobs:
  include:
    - name: 'Publish to Chromatic'
      script: npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes
    - name: 'run unit tests'
      script: npm run test:unit
    - name: 'test creating a build'
      script: npm run build
