version: '3'

networks:
  net:
    name: envidat-frontend

services:
  envidat-frontend:
    image: '${INTERNAL_REG}/envidat-frontend:debug'
    build:
      context: .
      target: debug
      args:
        INTERNAL_REG: ${INTERNAL_REG}
        EXTERNAL_REG: ${EXTERNAL_REG}
        MAINTAINER_APP: ${MAINTAINER_APP}
        MAINTAINER_CD: ${MAINTAINER_CD}
    container_name: envidat_frontend
    ports:
      - 8990:8080
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules/
    networks:
      - net
    restart: unless-stopped
