version: '3'

networks:
  ckan-internal:
    external: true

services:
  envidat-frontend:
    image: "${INTERNAL_REG}/envidat-frontend:${VERSION}-develop"
    container_name: envidat_frontend
    ports:
      - 8990:8080
    volumes:
      - ./src:/app/src:ro
    networks:
      - ckan-internal
    restart: unless-stopped
