version: '3'

networks:
  ckan-internal:
    external: true

services:
  envidat-frontend:
    image: "${INTERNAL_REG}/frontend:debug"
    build:
      context: .
      target: debug
      args:
        INTERNAL_REG: ${INTERNAL_REG}
        EXTERNAL_REG: ${EXTERNAL_REG}
        MAINTAINER_APP: ${MAINTAINER_APP}
        MAINTAINER_CD: ${MAINTAINER_CD}
    container_name: envidat_frontend
    ports:
      - 8990:8080
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules/
    networks:
      - ckan-internal
    restart: unless-stopped
