version: '3'

networks:
  ckan-internal:
    external: true
  traefik-proxy:
    external: true

services:
  envidat-frontend:
    image: "${INTERNAL_REG}/envidat-frontend:${VERSION}"
    container_name: envidat_frontend_prod
    networks:
      - ckan-internal
      - traefik-proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.envidat.rule=Host(`frontend.${HOST_ADDRESS}`)"
      - "traefik.http.routers.envidat.entrypoints=websecure"
      - "traefik.http.routers.envidat.tls=true"
      - "traefik.http.services.envidat.loadbalancer.server.port=80"