import Vue from 'vue';

export const eventBus = new Vue(
  // {
  // name: 'eventBus',
  // }
);
eventBus.$name = 'eventBus';

export const METADATA_OPEN_MODAL = 'METADATA_OPEN_MODAL';
export const METADATA_CLOSE_MODAL = 'METADATA_CLOSE_MODAL';

export const GCNET_OPEN_DETAIL_CHARTS = 'GCNET_OPEN_DETAIL_CHARTS';
export const GCNET_INJECT_MICRO_CHARTS = 'GCNET_INJECT_MICRO_CHARTS';

export const INJECT_RESOURCE_STRATEGY = 'INJECT_RESOURCE_STRATEGY';

export const OPEN_TEXT_PREVIEW = 'OPEN_TEXT_PREVIEW';
export const SELECT_EDITING_RESOURCE = 'SELECT_EDITING_RESOURCE';
export const SELECT_EDITING_RESOURCE_PROPERTY = 'id';
export const CANCEL_EDITING_RESOURCE = 'CANCEL_EDITING_RESOURCE';
export const SAVE_EDITING_RESOURCE = 'SAVE_EDITING_RESOURCE';

export const INJECT_TEXT_PREVIEW = 'INJECT_TEXT_PREVIEW';
export const INJECT_MAP_FULLSCREEN = 'INJECT_MAP_FULLSCREEN';

export const MAP_ZOOM_IN = 'MAP_ZOOM_IN';
export const MAP_ZOOM_OUT = 'MAP_ZOOM_OUT';
export const MAP_ZOOM_CENTER = 'MAP_ZOOM_CENTER';
export const MAP_COMPARE_START = 'MAP_COMPARE_START';
export const MAP_COMPARE_END = 'MAP_COMPARE_END';
export const MAP_TOGGLE_BASE_LAYER = 'MAP_TOGGLE_BASE_LAYER';

export const EDITMETADATA_OBJECT_UPDATE = 'EDITMETADATA_OBJECT_UPDATE';
export const EDITMETADATA_CUSTOMFIELDS = 'EDITMETADATA_CUSTOMFIELDS';
export const EDITMETADATA_MAIN_DESCRIPTION = 'EDITMETADATA_MAIN_DESCRIPTION';
export const EDITMETADATA_MAIN_HEADER = 'EDITMETADATA_MAIN_HEADER';
export const EDITMETADATA_PUBLICATION_INFO = 'EDITMETADATA_PUBLICATION_INFO';

export const EDITMETADATA_DATA_RESOURCES = 'EDITMETADATA_DATA_RESOURCES';
