export default {
  author:
    '[{"name": "Risch", "data_credit": ["collection", "validation", "publication"], "affiliation": "Swiss Federal Institute for Forest, Snow and Landscape Research, Switzerland", "affiliation_03": "", "affiliation_02": "", "identifier": "0000-0003-0531-8336", "email": "anita.risch@wsl.ch", "given_name": "Anita C."}, {"name": "Báez Jacome", "data_credit": ["collection", "publication"], "email": "selene.baez@epn.edu.ec", "affiliation": "Escuela Politécnica Nacional del Ecuador, Ecuador.", "affiliation_03": "", "affiliation_02": "", "identifier": "", "given_name": "Selene V."}, {"name": "Biederman", "data_credit": ["collection", "publication"], "email": "lbied@iastate.edu", "affiliation": "Iowa State University, USA", "affiliation_03": "", "given_name": "Lori A.", "identifier": "", "affiliation_02": ""}, {"name": "Zimmermmann", "data_credit": ["collection", "validation", "publication"], "affiliation": "Swiss Federal Institute for Forest, Snow and Landscape Research, Switzerland", "affiliation_03": "", "given_name": "Stephan", "identifier": "", "email": "stephan.zimmermann@wsl.ch", "affiliation_02": ""}, {"name": "Blair", "data_credit": ["collection", "publication"], "email": "jblair@ksu.edu", "affiliation": "Kansas State University, USA", "affiliation_03": "", "given_name": "John M.", "identifier": "", "affiliation_02": ""}, {"name": "Brown", "data_credit": ["collection", "publication"], "affiliation": "Colorado State University, USA", "affiliation_03": "", "given_name": "Cynthia S.", "identifier": "", "email": "cynthia.s.brown@colostate.edu", "affiliation_02": ""}, {"name": "Caldeira", "data_credit": ["collection", "publication"], "email": "mcaldeira@isa.ulisboa.pt", "affiliation": "Universidade de Lisboa, Portugal", "affiliation_03": "", "affiliation_02": "", "identifier": "", "given_name": "Maria C."}, {"name": "Collins", "data_credit": ["collection", "publication"], "affiliation": "University of New Mexico, USA", "affiliation_03": "", "affiliation_02": "", "identifier": "", "email": "scollins@unm.edu", "given_name": "Scott L."}, {"name": "Daleo", "data_credit": ["collection", "publication"], "email": "pdaleo@mdp.edu.ar", "affiliation": "Universidad Nacional de Mar del Plata, Argentina", "affiliation_03": "", "given_name": "Pedro", "identifier": "", "affiliation_02": ""}, {"name": "di Virgilio", "data_credit": ["collection", "publication"], "affiliation": "Universidad Nacional del Comahue, Argentina", "affiliation_03": "", "given_name": "Agustina", "identifier": "", "email": "adivirgilio@comahue-conicet.gob.ar", "affiliation_02": ""}, {"name": "Ebeling", "data_credit": ["collection", "publication"], "email": "anne.ebeling@uni-jena.de", "affiliation": "University Jena, Germany", "affiliation_03": "", "given_name": "Anne", "identifier": "", "affiliation_02": ""}, {"name": "Seabloom", "data_credit": ["collection", "publication"], "email": "seabloom@umn.edu", "affiliation": "Swiss Federal Institute for Forest, Snow and Landscape Research", "affiliation_03": "", "given_name": "Eric W.", "identifier": "", "affiliation_02": ""}, {"name": "Eisenhauer", "data_credit": ["collection", "publication"], "affiliation": "German Centre for Integrative Biodiversity Research (iDiv) , Germany", "affiliation_03": "", "given_name": "Nico", "identifier": "", "email": "nico.eisenhauer@idiv.de", "affiliation_02": ""}, {"name": "Esch", "data_credit": ["collection", "publication"], "email": "eesch@uoguelph.ca", "affiliation": "University of California San Diego, USA", "affiliation_03": "", "given_name": "Ellen", "identifier": "", "affiliation_02": ""}, {"name": "Eskelinen", "data_credit": ["collection", "publication"], "email": "anu.eskelinen@idiv.de", "affiliation": "Helmholtz Center for Environmental Research – UFZ, Germany", "affiliation_03": "", "affiliation_02": "", "identifier": "", "given_name": "Anu"}, {"name": "Ochoa-Hueso", "data_credit": ["validation", "publication"], "affiliation": "University of Cádiz, Spain", "affiliation_03": "", "affiliation_02": "", "identifier": "0000-0002-1839-6926", "email": "rochoahueso@gmail.com", "given_name": "Raul"}, {"name": "Hagenah", "data_credit": ["collection", "publication"], "affiliation": "University of Pretoria, South Africa", "affiliation_03": "", "given_name": "Nicole", "identifier": "", "email": "nicole.hagenah@up.ac.za", "affiliation_02": ""}, {"name": "Hautier", "data_credit": ["collection", "publication"], "email": "y.hautier@uu.nl", "affiliation": "Utrecht University, The Netherlands.", "affiliation_03": "", "affiliation_02": "", "identifier": "", "given_name": "Yann"}, {"name": "Kirkman", "data_credit": ["collection", "publication"], "email": "kirkmank@ukzn.ac.za", "affiliation": "University of KwaZulu-Natal, South Africa", "affiliation_03": "", "given_name": "Kevin P.", "identifier": "", "affiliation_02": ""}, {"name": "MacDougall", "data_credit": ["collection", "publication"], "email": "amacdo02@uoguelph.ca", "affiliation": "University of Guelph, Canada", "affiliation_03": "", "affiliation_02": "", "identifier": "", "given_name": "Andrew S."}, {"name": "Moore", "data_credit": ["collection", "publication"], "affiliation": "Monash University, Australia", "affiliation_03": "", "affiliation_02": "", "identifier": "", "email": "joslin.moore@monash.edu", "given_name": "Joslin L."}, {"name": "Power", "data_credit": ["collection", "publication"], "email": "s.power@westernsydney.edu.au", "affiliation": "Western Sydney University, Australia.", "affiliation_03": "", "affiliation_02": "", "identifier": "", "given_name": "Sally A."}, {"name": "Harpole", "data_credit": ["collection", "publication"], "affiliation": "Helmholtz Center for Environmental Research – UFZ, Germany", "affiliation_03": "", "affiliation_02": "", "identifier": "", "email": "stan.harpole@ufz.de", "given_name": "W. Stanley"}, {"name": "Prober", "data_credit": ["collection", "publication"], "email": "suzanne.prober@csiro.au", "affiliation": "CSIRO Land and Water, Australia", "affiliation_03": "", "affiliation_02": "", "identifier": "", "given_name": "Suzanne M."}, {"name": "Roscher", "data_credit": ["collection", "publication"], "affiliation": "Helmholtz Center for Environmental Research – UFZ, Germany", "affiliation_03": "", "affiliation_02": "", "identifier": "", "email": "christiane.roscher@ufz.de", "given_name": "Christiane"}, {"name": "Sankaran", "data_credit": ["collection", "publication"], "email": "mahesh@ncbs.res.in", "affiliation": "National Centre for Biological Sciences,  India", "affiliation_03": "", "given_name": "Mahesh", "identifier": "", "affiliation_02": ""}, {"name": "Siebert", "data_credit": ["collection", "publication"], "affiliation": "German Centre for Integrative Biodiversity Research (iDiv) , Germany", "affiliation_03": "", "affiliation_02": "", "identifier": "", "email": "julia.siebert@idiv.de", "given_name": "Julia"}, {"name": "Schütz", "data_credit": ["collection", "validation", "publication"], "affiliation": "Swiss Federal Institute for Forest, Snow and Landscape Research, Switzerland", "affiliation_03": "", "affiliation_02": "", "identifier": "", "email": "martin.schuetz@wsl.ch", "given_name": "Martin"}, {"name": "Speziale", "data_credit": ["collection", "publication"], "email": "karina.speziale@comahue-conicet.gob.ar", "affiliation": "Universidad Nacional del Comahue, Argentina", "affiliation_03": "", "given_name": "Karina L.", "identifier": "", "affiliation_02": ""}, {"name": "Tognetti", "data_credit": ["collection", "publication"], "email": "tognetti@agro.uba.ar", "affiliation": "Universidad de Buenos Aires, Argentina.", "affiliation_03": "", "given_name": "Pedro", "identifier": "", "affiliation_02": ""}, {"name": "Virtanen", "data_credit": ["collection", "publication"], "email": "risto.virtanen@oulu.fi", "affiliation": "Helmholtz Center for Environmental Research – UFZ, Germany", "affiliation_03": "", "given_name": "Risto", "identifier": "", "affiliation_02": ""}, {"name": "Yahdjian", "data_credit": ["collection", "publication"], "affiliation": "Universidad de Buenos Aires, Argentina", "affiliation_03": "", "affiliation_02": "", "identifier": "", "email": "yahdjian@agro.uba.ar", "given_name": "Laura"}, {"name": "Moser", "data_credit": ["validation", "publication"], "email": "barbara.moser@wsl.ch", "affiliation": "Swiss Federal Institute for Forest, Snow and Landscape Research, Switzerland", "affiliation_03": "", "affiliation_02": "", "identifier": "", "given_name": "Barbara"}, {"name": "Knops", "data_credit": ["collection", "publication"], "email": "jknops2@unl.edu", "affiliation": "University of Nebraska, USA", "affiliation_03": "", "affiliation_02": "", "identifier": "", "given_name": "Johannes M.H."}, {"name": "Frey", "data_credit": ["collection", "validation", "publication"], "affiliation": "Swiss Federal Institute for Forest, Snow and Landscape Research, Switzerland", "affiliation_03": "", "affiliation_02": "", "identifier": "", "email": "beat.frey@wsl.ch", "given_name": "Beat"}, {"name": "Firn", "data_credit": ["collection", "validation", "publication"], "email": "jennifer.firn@qut.edu.au", "affiliation": "Queensland University of Technology, Australia", "affiliation_03": "", "affiliation_02": "", "identifier": "", "given_name": "Jennifer"}, {"name": "Fay", "data_credit": ["collection", "validation", "publication"], "affiliation": "USDA-ARS Grassland, Soil, and Water Research Laborator, USA", "affiliation_03": "", "affiliation_02": "", "identifier": "", "email": "philip.fay@ars.usda.gov", "given_name": "Philip A."}, {"name": "Hagedorn", "data_credit": ["validation", "publication"], "email": "frank.hagedorn@wsl.ch", "affiliation": "Swiss Federal Institute for Forest, Snow and Landscape Research, Switzerland", "affiliation_03": "", "given_name": "Frank", "identifier": "", "affiliation_02": ""}, {"name": "Borer", "data_credit": ["collection", "publication"], "email": "borer@umn.edu", "affiliation": "University of Minnesota, USA", "affiliation_03": "", "affiliation_02": "", "identifier": "", "given_name": "Elizabeth T."}, {"name": "McCulley", "data_credit": ["collection", "publication"], "affiliation": "University of Kentucky, USA", "affiliation_03": "", "given_name": "Rebecca L.", "identifier": "", "email": "rebecca.mcculley@uky.edu", "affiliation_02": ""}, {"name": "Broadbent", "data_credit": ["collection", "publication"], "affiliation": "The University of Manchester, United Kingdom", "affiliation_03": "", "given_name": "Arthur A.D.", "identifier": "", "email": "broadbent.arthur@gmail.com", "affiliation_02": ""}, {"name": "Stevens", "data_credit": ["collection", "publication"], "email": "c.stevens@lancaster.ac.uk", "affiliation": "Lancaster University, United Kingdom", "affiliation_03": "", "given_name": "Carly J.", "identifier": "", "affiliation_02": ""}, {"name": "Silveira", "data_credit": ["collection", "publication"], "affiliation": "University of Florida, USA", "affiliation_03": "", "given_name": "Maria L.", "identifier": "", "email": "mlas@ufl.edu", "affiliation_02": ""}, {"name": "Adler", "data_credit": ["collection", "publication"], "affiliation": "Utah State University, USA", "affiliation_03": "", "affiliation_02": "", "identifier": "", "email": "peter.adler@usu.edu", "given_name": "Peter B."}]',
  author_email: null,
  creator_user_id: 'd30dde41-6b11-44de-9191-23cdd5bda0e9',
  date: '[{"date": "2015-01-01", "date_type": "created", "end_date": "2016-12-31"}]',
  doi: '10.16904/envidat.87',
  funding:
    '[{"grant_number": "two internal competitive WSL grants", "institution": "WSL", "institution_url": ""}, {"grant_number": "NSF-DEB-1042132", "institution": "National Science Foundation Research Coordination Network", "institution_url": ""}, {"grant_number": "NSF-DEB-1234162", "institution": "Long-Term Ecological Research (LTER)", "institution_url": ""}, {"grant_number": "DG-0001-13", "institution": "Institute on the Environment at the University of Minnesota", "institution_url": ""}]',
  id: '109ef559-0459-4056-aff5-282374d01ff9',
  isopen: true,
  language: 'en',
  license_id: 'odc-odbl',
  license_title: 'ODbL with Database Contents License (DbCL)',
  license_url: 'https://opendefinition.org/licenses/odc-odbl',
  maintainer:
    '{"affiliation": "Swiss Federal Institute for Forest, Snow and Landscape Research, Switzerland", "identifier": "0000-0003-0531-8336", "given_name": "Anita C.", "name": "Risch", "email": "anita.risch@wsl.ch"}',
  maintainer_email: null,
  metadata_created: '2019-10-03T12:14:24.833422',
  metadata_modified: '2020-08-13T12:53:54.475100',
  name: 'soil-net-nitrogen-mineralisation-across-global-grasslands',
  notes:
    'This dataset contains all data on which the following publication below is based.\r\n\r\nPaper Citation:\r\n\r\nRisch, A. C.; Zimmermann, S.; Ochoa-Hueso, R.; Schütz, M.; Frey, B.; Firn, J. L.; Fay, P. A.; Hagedorn, F.; Borer, E. T.; Seabloom, E. W.; et al. Soil net nitrogen mineralisation across global grasslands. Nat. Commun. 2019, 10 (1), 4981 (10 pp.). doi.org/10.1038/s41467-019-12948-2\r\n\r\nPlease cite this paper together with the citation for the datafile.\r\n\r\nWe conducted coordinated measurements of realised and potential soil net Nmin, and assessed water holding capacity, bulk density, C and N content, texture, pH, pore space, microbial biomass, and archaeal (AOA) and bacterial (AOB) ammonia oxidiser abundance using identical materials and methods across 30 grasslands on six continents. The sites covered a globally relevant range of climatic and edaphic conditions. Climate data was obtained from worldclim - Global climate data https://www.worldclim.org/',
  num_resources: 1,
  num_tags: 8,
  organization: {
    id: '60e92a46-5f9b-4a06-a32e-6a5e04869486',
    name: 'plant-animal-interactions',
    title: 'Plant-Animal Interactions',
    type: 'organization',
    description:
      'We are studying the distribution of and interactions among producers, consumers as well as decomposers and between these communities and their environment. We focus on food webs in real world ecosystems and thus mainly sample our data during experimental field campaigns. Data collection under controlled conditions in the greenhouse or experimental garden are, however, common add-ons hereby. We are mainly interested in the functioning of natural ecosystems and often conduct research in National Parks around the world. Our main study area is, however, the Swiss National Park. While working on basic research questions, we regularly consider applied aspects that are related to protecting or conserving endangered ecosystems.\r\n\r\nExamples of research question of our research group assesses are:\r\n\r\nHow is species loss related to ecosystem processes and functions? Which species or species groups are particularly relevant for ecosystem functioning? Which effects are expected with the loss of such important species groups? How are aboveground organisms interacting with belowground organisms? Which abiotic and biotic conditions favor diverse ecosystems? Is global change (for example eutrophication, habitat fragmentation, climate) a thread for diverse ecosystems? How can diverse ecosystems be protected?',
    image_url: '2018-07-10-090227.680797LogoWSL.svg',
    created: '2018-04-20T09:51:26.756810',
    is_organization: true,
    approval_status: 'approved',
    state: 'active',
  },
  owner_org: '60e92a46-5f9b-4a06-a32e-6a5e04869486',
  private: false,
  publication: '{"publisher": "EnviDat", "publication_year": "2019"}',
  publication_state: 'published',
  related_datasets: '',
  related_publications: '* wsl:21835',
  resource_type: 'dataset',
  resource_type_general: 'dataset',
  spatial:
    '{"type":"Polygon","coordinates":[[[-140.2734375,-40.84706035607121],[-140.2734375,56.26776108757582],[153.6328125,56.26776108757582],[153.6328125,-40.84706035607121],[-140.2734375,-40.84706035607121]]]}',
  spatial_info: 'Global',
  state: 'active',
  subtitle: '',
  title: 'Soil net nitrogen mineralisation across global grasslands',
  type: 'dataset',
  url: null,
  version: '1.0',
  extras: [
    {
      key: 'dora_link',
      value: '',
    },
  ],
  resources: [
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2019-10-03T12:21:41.111259',
      description:
        'site.code: Site code\r\n\r\nContinent: Continent\r\n\r\nsampleID: Sample ID\r\n\r\nnn.latitude: Lattitude\r\n\r\nnn.longitude: Longitude\r\n\r\nbioclim.T.ann: Mean annual temperature (°C)\r\n\r\nbioclim.T.var: Temperature variability (°C)\r\n\r\nbioclim.T.q.wet: Temperature of the wettest quarter (°C)\r\n\r\nbioclim.T.q.dry: Temperature of the driest quarter (°C)\r\n\r\nbioclim.T.q.warm: Temperature of the warmest quarter (°C)\r\n\r\nbioclim.P.ann: Mean annual preciptiation (mm)\r\n\r\nbioclim.P.q.wet: Precipitation of the wettest quarter (mm)\r\n\r\nch.pH: pH\r\n\r\nch.WSK.vol: Water holding capacity (vol%)\r\n\r\nch.bulkdensity.gcm3: Bulk density (g cm-3)\r\n\r\nch.porespace: Pore space (vol%)\r\n\r\nch.sand.perc: Soil texture: sand (%)\r\n\r\nch.silt.perc: Soil texture: silt (%)\r\n\r\nch.clay.perc: Soil texture: clay (%)\r\n\r\nch.NO3start.mgg: NO3 at the beginning of the incubation (mgkg)\r\n\r\nch.Ntot.perc: Total soil N (%)\r\n\r\nch.Ctot.perc: Total soil C (%)\r\n\r\nch.Corg.perc: Soil organic C  (%)\r\n\r\nch.netNminfield.mgkgd: Realised soil net N mineralisation (mg kg-1 d-1)\r\n\r\nch.netNminlab.mgkgd: Potential soil ne N mineralisation (mg kg-1 d-1)\r\n\r\narchaea.cpg.log: Ammonia oxidising archaea (archaeal amoA gene copies g-1 soil)\r\n\r\nbacteria.cpg.log: Ammonia oxidising bacteria (bacterial amoA gene copies g-1 soil)\r\n\r\nmicr.biom: Microbial biomass (ug g-1 soil)\r\n\r\nch.CtoN: C to N ratio\r\n\r\nch.netNnitriffield.mgkgd.sqrt: Realised soil net nitrification, transformed (mg kg-1 d-1)\r\n\r\nch.netNammoniffield.mgkgd.sqrt: Realised soil net ammonification, transformed (mg kg-1 d-1)\r\n\r\nch.netNnitriflab.mgkgd.sqrt: Potential soil net nitrification, transformed (mg kg-1 d-1)\r\n\r\nch.netNammoniflab.mgkgd.sqrt: Potential soil net ammonifiation, transformed (mg kg-1 d-1)',
      doi: '',
      format: 'XLSX',
      hash: '',
      id: '24108011-8b7b-4da0-9742-2f05576ecbc1',
      last_modified: '2019-10-04T10:41:53.787263',
      metadata_modified: null,
      mimetype: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      mimetype_inner: null,
      name: 'soil-net-nitrogen-mineralisation-across-global-grasslands',
      package_id: '109ef559-0459-4056-aff5-282374d01ff9',
      position: 0,
      resource_type: null,
      restricted: '{"shared_secret": "", "allowed_users": "", "level": "public"}',
      size: 33527,
      state: 'active',
      url: 'https://www.envidat.ch/dataset/109ef559-0459-4056-aff5-282374d01ff9/resource/24108011-8b7b-4da0-9742-2f05576ecbc1/download/risch-et-al._soil-net-nitrogen-mineralisation-aross-global-grasslands.xlsx',
      url_type: 'upload',
    },
  ],
  tags: [
    {
      display_name: 'GLOBAL',
      id: 'b1ba37d9-d9b7-4164-b39e-dba40a734415',
      name: 'GLOBAL',
      state: 'active',
      vocabulary_id: null,
    },
    {
      display_name: 'GRASSLAND',
      id: 'fa420fc0-5693-4358-bc61-4951b239457c',
      name: 'GRASSLAND',
      state: 'active',
      vocabulary_id: null,
    },
    {
      display_name: 'MINERALIZATION',
      id: '8fc4e920-34d8-459f-86f2-3630c74cba6b',
      name: 'MINERALIZATION',
      state: 'active',
      vocabulary_id: null,
    },
    {
      display_name: 'NUTRIENT NETWORK',
      id: '38d83a60-ebab-4d30-b968-d6cf7e070066',
      name: 'NUTRIENT NETWORK',
      state: 'active',
      vocabulary_id: null,
    },
    {
      display_name: 'SOIL',
      id: '024cba10-0afd-4231-b6fc-7657536a5c05',
      name: 'SOIL',
      state: 'active',
      vocabulary_id: null,
    },
    {
      display_name: 'SOIL BIOLOGY',
      id: '7a407b54-15dc-4c47-bce7-6e35e812f65e',
      name: 'SOIL BIOLOGY',
      state: 'active',
      vocabulary_id: null,
    },
    {
      display_name: 'SOIL CHEMISTRY',
      id: 'db9bbced-c332-45c7-a793-a5291d06923b',
      name: 'SOIL CHEMISTRY',
      state: 'active',
      vocabulary_id: null,
    },
    {
      display_name: 'WORLDWIDE',
      id: 'dd2103f8-8f9a-4443-9fb4-6983f1df4b0b',
      name: 'WORLDWIDE',
      state: 'active',
      vocabulary_id: null,
    },
  ],
  groups: [],
  relationships_as_subject: [],
  relationships_as_object: [],
};
