export default {
  author:
    '[{"affiliation": "WSL", "affiliation_02": "ETHZ", "affiliation_03": "EPFL", "data_credit": ["collection", "validation", "curation", "software", "supervision"], "email": "konrad.steffen@wsl.ch", "given_name": "Konrad", "identifier": "", "name": "Steffen (&#8224;)"}, {"affiliation": "WSL", "affiliation_02": "", "affiliation_03": "", "data_credit": ["validation", "curation", "software", "publication"], "email": "derek.houtz@wsl.ch", "given_name": "Derek", "identifier": "", "name": "Houtz"}, {"affiliation": "GEUS", "affiliation_02": "", "affiliation_03": "", "data_credit": ["validation", "software"], "email": "bav@geus.dk", "given_name": "Baptiste", "identifier": "0000-0002-4169-8973", "name": "Vandecrux"}, {"affiliation": "University of Colorado", "affiliation_02": "CIRES", "affiliation_03": "", "data_credit": "collection", "email": "waleed.abdalati@colorado.edu", "given_name": "Waleed", "identifier": "", "name": "Abdalati"}, {"affiliation": "UNAVCO", "affiliation_02": "", "affiliation_03": "", "data_credit": ["collection", "validation", "software"], "email": "bayou_nicolas@yahoo.com", "given_name": "Nicolas", "identifier": "", "name": "Bayou"}, {"affiliation": "Geological Survey of Denmark and Greenland", "affiliation_02": "", "affiliation_03": "", "data_credit": ["collection", "validation", "curation", "software"], "email": "jeb@geus.dk", "given_name": "Jason", "identifier": "", "name": "Box"}, {"affiliation": "Geological Survey of Denmark and Greenland", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "wic@geus.dk", "given_name": "William", "identifier": "", "name": "Colgan"}, {"affiliation": "WSL", "affiliation_02": "", "affiliation_03": "", "data_credit": "software", "email": "lucia.espona@wsl.ch", "given_name": "Lucia", "identifier": "0000-0002-1477-6999", "name": "Espona Pernas"}, {"affiliation": "SLF", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "nena.griessinger@gmail.com", "given_name": "Nena", "identifier": "", "name": "Griessinger"}, {"affiliation": "WSL", "affiliation_02": "", "affiliation_03": "", "data_credit": "software", "email": "dominik.haas@wsl.ch", "given_name": "Dominik", "identifier": "", "name": "Haas-Artho"}, {"affiliation": "Ludwig-Maximilians-Universität München", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "heilig@r-hm.de", "given_name": "Achim", "identifier": "", "name": "Heilig"}, {"affiliation": "International Polar Foundation (IPF)", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "alain.hubert@polarfoundation.org", "given_name": "Alain", "identifier": "", "name": "Hubert"}, {"affiliation": "WSL", "affiliation_02": "", "affiliation_03": "", "data_credit": ["software", "publication"], "email": "ionut.iosifescu@wsl.ch", "given_name": "Ionuț", "identifier": "0000-0002-1770-7833", "name": "Iosifescu Enescu"}, {"affiliation": "International Polar Foundation (IPF)", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "gg@polarfoundation.org", "given_name": "Nighat", "identifier": "", "name": "Johnson-Amin"}, {"affiliation": "GEUS", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "nbk@geus.dk", "given_name": "Nanna B.", "identifier": "", "name": "Karlsson"}, {"affiliation": "WSL", "affiliation_02": "", "affiliation_03": "", "data_credit": "software", "email": "rebecca.kurup@wsl.ch", "given_name": "Rebecca", "identifier": "", "name": "Kurup"}, {"affiliation": "Colorado State University", "affiliation_02": "", "affiliation_03": "", "data_credit": ["collection", "validation", "curation", "software"], "email": "daniel.mcgrath@colostate.edu", "given_name": "Daniel", "identifier": "", "name": "McGrath"}, {"affiliation": "WSL", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "reza.naderpour@wsl.ch", "given_name": "Reza", "identifier": "", "name": "Naderpour"}, {"affiliation": "GEUS", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "aoep@geus.dk", "given_name": "Allan Østerby", "identifier": "", "name": "Pederson"}, {"affiliation": "British Antarctic Survey", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "biaper@bas.ac.uk", "given_name": "Bianca", "identifier": "", "name": "Perren"}, {"affiliation": "Swiss Re", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "phillitp@colorado.edu", "given_name": "Thomas", "identifier": "", "name": "Phillips"}, {"affiliation": "WSL", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "gian-kasper.plattner@wsl.ch", "given_name": "Gian-Kasper", "identifier": "", "name": "Plattner"}, {"affiliation": "geoformer igp AG", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "m.proksch@geoformer.ch", "given_name": "Martin", "identifier": "", "name": "Proksch"}, {"affiliation": "GEUS", "affiliation_02": "Copenhagen University", "affiliation_03": "", "data_credit": "software", "email": "maiken.revheim@outlook.com", "given_name": "Maiken Kristiansen", "identifier": "", "name": "Revheim"}, {"affiliation": "RHB", "affiliation_02": "", "affiliation_03": "", "email": "martina.saettele@rhb.ch", "given_name": "Martina", "identifier": "", "name": "Saettele"}, {"affiliation": "SLF", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "schneebeli@slf.ch", "given_name": "Martin", "identifier": "", "name": "Schneebeli"}, {"affiliation": "UCAR", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "ksampson@ucar.edu", "given_name": "Kevin", "identifier": "", "name": "Sampson"}, {"affiliation": "NOAA", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "sandy.starkweather@noaa.gov", "given_name": "Sandy", "identifier": "", "name": "Starkweather"}, {"affiliation": "Climanosco", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "simon.steffen@colorado.edu", "given_name": "Simon", "identifier": "", "name": "Steffen"}, {"affiliation": "University of Manitoba", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "Julienne.Stroeve@umanitoba.ca", "given_name": "Julienne", "identifier": "", "name": "Stroeve"}, {"affiliation": "SLF", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "benjamin.walter@slf.ch", "given_name": "Benjamin", "identifier": "", "name": "Walter"}, {"affiliation": "GEUS", "affiliation_02": "", "affiliation_03": "", "data_credit": "collection", "email": "oew@geus.dk", "given_name": "Øyvind Andreas", "identifier": "", "name": "Winton"}, {"affiliation": "NASA GSFC", "affiliation_02": "", "affiliation_03": "", "data_credit": ["collection", "supervision"], "email": "jayzwallyice@verizon.net", "given_name": "Jay", "identifier": "", "name": "Zwally"}]',
  author_email: null,
  creator_user_id: 'd6ddb606-7a2b-4210-9ae3-8faf5e7dfcb2',
  date: '[{"date": "1996-05-01", "date_type": "collected", "end_date": ""}]',
  doi: '10.16904/envidat.1',
  funding:
    '[{"grant_number": "", "institution": "WSL", "institution_url": ""}, {"grant_number": "", "institution": "NOAA", "institution_url": ""}, {"grant_number": "", "institution": "NASA", "institution_url": ""}]',
  id: '4be8caec-be03-4500-810b-3002c964d3b7',
  isopen: false,
  language: 'en',
  license_id: 'other-undefined',
  license_title: 'Other (Specified in the description)',
  maintainer:
    '{"affiliation": "WSL", "email": "derek.houtz@wsl.ch", "given_name": "Derek", "identifier": "", "name": "Houtz"}',
  maintainer_email: null,
  metadata_created: '2020-10-08T13:21:40.277450',
  metadata_modified: '2022-11-01T14:57:25.863206',
  name: 'gcnet',
  notes:
    '## In Memory of Dr. Konrad (Koni) Steffen \r\n\r\n<br />\r\n<br />\r\n\r\nUpdate October 2022: The GC-Net is kindly continued by the Geological Survey of Denmark and Greenland (GEUS). \r\nStarting October 3, 2022, the access to the latest versions of the "ready to use" L1 data has been migrated to GEUS. Future data versions will be available at: https://doi.org/10.22008/FK2/VVXGUT\r\n\r\n### Background \r\n\r\nStarting with a single station in 1991, the Greenland Climate Network (commonly known as GC-Net) is a set of Automatic Weather Stations (AWS) set up and managed by the late Prof. Dr. Konrad (Koni) Steffen, and spanning the Greenland Ice Sheet (GrIS). This first station was "Swiss Camp" or the "ETH-CU" camp (GC-Net station #01) which was used as a field science and education site by Koni for years. The GC-Net was expanded with multiple NASA, NOAA, and NSF grants throughout the years, and then supported by WSL in the later years. These data (see "C-file" below) were previously hosted by the Cooperative Institute for Research in Environmental Sciences (CIRES) in Boulder, Colorado. \r\n\r\n\r\n### Overview \r\n\r\nProvided in this dataset are the 16 longest running stations in the network, which are spread over a significant area of the GrIS and the majority of the unique climatic zones. From the South Dome high point in the South, to the Western Jakobshavn ablation region in the west, to the Petermann glacier in the North across east of the Northeast Greenland Ice Stream to the east, GC-Net is the longest running climatological record of Greenland. \r\n\r\n\r\n### The standard GC-Net station consists of: \r\n\r\n* Air temperature measurements at 2 heights above the surface\r\n* Temperature and humidity measurements at 2 heights above the surface\r\n* Wind speed and direction measured at 2 heights above the surface\r\n* Sonic distance sounder measurements for 2 snow height and distance of instruments to surface\r\n* Incoming shortwave radiation measurement\r\n* Reflected shortwave radiation measurement\r\n* Net broadband radiation (long- and short-wave) measurement\r\n* Air pressure measurement\r\n\r\nData have often been repatriated in near-real time using one of either the GOES geostationary satellite or the ARGOS polar orbiting satellite transmission system. The stations were visited typically every 1-2 years for maintenance and service, and to download full uncorrupted data directly from the dataloggers. GC-Net stations were visited by Twin Otter equipped with snow skids to land directly on the open-ice at the AWS locations, or by helicopter near the west coast. The AWSs operate on solar and battery power and occasionally lost power during the dark and cold winter months, particularly when the batteries were aging. \r\n\r\n\r\n### Dataset \r\n\r\nThis dataset consists of 2 main data levels; Level 0 and Level 1. \r\nLevel 0 is the raw data from the dataloggers, historical processing codes, satellite transmissions, and Koni’s personal data archive. Level 0 data (.zip) directories contain subdirectories: \r\n\r\n* “C file” - contains the historical processed datafile for each station.\r\n\r\n* “Campbell logger files” - contains the raw csv datafiles from the stations’ Campbell Scientific dataloggers since the CR1000 era (~2007-2008 for most stations).\r\n\r\n* “Photos” - contains photographs of the station when available marked by year.\r\n\r\nLevel 1 is the appended, calibrated, cleaned, and quality flagged data. The full processing scheme is open-source and publicly available on the following GitHub repository (please also check GitHub for the latest L1 data):\r\n\r\n[GC-Net L1 data on GitHub](https://github.com/GEUS-Glaciology-and-Climate/GC-Net-level-1-data-processing "GC-Net-level-1-data-processing")\r\n\r\nLevel 1 data is provided in the newly described csv-compatible [NEAD format](https://www.envidat.ch/#/metadata/nead "NEAD format").\r\n\r\n<br />\r\n\r\n### Additional Details \r\n\r\nDataset description publication will be forthcoming. \r\nThe Geological Survey of Denmark and Greenland (GEUS) has been imperative in the reprocessing and continuity mission of GC-Net. Multiple GC-Net stations have been replaced with updated and upgraded AWS hardware at the same coordinates by GEUS. This effort will ensure continuity of the GC-Net dataset into the future.  \r\n',
  num_resources: 21,
  num_tags: 6,
  organization: {
    id: '332fe580-e16f-4e2e-9018-be65e430a3a0',
    name: 'wsl',
    title: 'WSL',
    type: 'organization',
    description:
      'The Swiss Federal Institute for Forest, Snow and Landscape Research is concerned with the use, development and protection of natural and urban spaces. The focus of our research is on solving problems to do with the responsible use of landscapes and forests and a prudent approach to natural hazards, especially those common in mountainous countries. WSL occupies a leading position internationally in these research areas. We also provide groundwork for sustainable environmental policies in Switzerland.\r\n\r\n__Further information__: http://www.wsl.ch',
    image_url: '2020-11-04-134216.5237452000px-LogoWSL.svg.png',
    created: '2016-05-24T16:16:47.680185',
    is_organization: true,
    approval_status: 'approved',
    state: 'active',
  },
  owner_org: '332fe580-e16f-4e2e-9018-be65e430a3a0',
  private: false,
  publication: '{"publication_year": "2020", "publisher": "EnviDat"}',
  publication_state: 'published',
  related_datasets: '',
  related_publications:
    '*Steffen, K. and Box, J., 2001. Surface climatology of the Greenland ice sheet: Greenland Climate Network 1995–1999. Journal of Geophysical Research: Atmospheres, 106(D24), pp.33951-33964. https://doi.org/10.1029/2001JD900161\r\n\r\n*Steffen, K., Huff, N.C.R., Starkweather, S., Albert, T. and McAllister, M., 2003. Variability and forcing of climate parameters on the Greenland Ice Sheet: Greenland climate Network (GC-NET). National Aeronautics and Space Administration.\r\n\r\n*Fausto, R.S., van As, D., Mankoff, K.D., Vandecrux, B., Citterio, M., Ahlstrøm, A.P., Andersen, S.B., Colgan, W., Karlsson, N.B., Kjeldsen, K.K. and Korsgaard, N.J., 2021. Programme for Monitoring of the Greenland Ice Sheet (PROMICE) automatic weather station data. Earth System Science Data, 13(8), pp.3819-3845. https://doi.org/10.5194/essd-13-3819-2021\r\n\r\n*Ionuț Iosifescu Enescu; Mathias Bavay; Kenneth Mankoff (2020). Non-Binary Environmental Archive Data (NEAD) format. EnviDat. doi: 10.16904/envidat.187.\r\n',
  resource_type: 'dataset',
  resource_type_general: 'dataset',
  spatial:
    '{"type":"Polygon","coordinates":[[[-69.2578125,58.92884056311852],[-69.2578125,83.22122652790935],[-10.1953125,83.22122652790935],[-10.1953125,58.92884056311852],[-69.2578125,58.92884056311852]]]}',
  spatial_info: 'Switzerland',
  state: 'active',
  subtitle: '',
  title: 'Greenland Climate Network (GC-Net) Data',
  type: 'dataset',
  url: null,
  version: '1.0',
  resources: [
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2022-10-03T14:12:06.054508',
      description:
        'The GC-Net is kindly continued by the Geological Survey of Denmark and Greenland (GEUS). \r\n\r\nStarting October 3, 2022, the access to the latest versions of the "ready to use" L1 data has been migrated to GEUS, (doi:10.22008/FK2/VVXGUT). Future versions will be available from GEUS, while the initial version of L1 data has been archived.\r\n\r\n',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: 'f5a9251c-9959-467d-91ac-48258b4da053',
      last_modified: null,
      metadata_modified: '2022-10-03T14:55:21.860176',
      mimetype: null,
      mimetype_inner: null,
      name: 'Access the latest L1 data ',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 0,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: null,
      state: 'active',
      url:
        'https://dataverse.geus.dk/dataset.xhtml?persistentId=doi:10.22008/FK2/VVXGUT',
      url_type: null,
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-10-08T13:23:10.296524',
      description:
        'The GC-Net is kindly continued by the Geological Survey of Denmark and Greenland (GEUS). \r\n\r\nStarting October 3, 2022, the access to the latest versions of the "ready to use" L1 data has been migrated to GEUS, (doi:10.22008/FK2/VVXGUT). Future versions will be available from GEUS, while the initial versions of L0 and L1 data have been archived.',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: '635ee652-5de0-4141-a0de-31c5d6ccb805',
      last_modified: null,
      metadata_modified: '2022-10-25T14:22:51.609731',
      mimetype: null,
      mimetype_inner: null,
      name: 'Archived GC-Net Data (deprecated)',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 1,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: null,
      state: 'active',
      url:
        'https://envicloud.wsl.ch/#/?prefix=gcnet/data/wsl-geus-cooperation/',
      url_type: null,
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T14:53:10.163969',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: 'ce5535e4-1004-440c-907e-8e72f2902307',
      last_modified: '2020-11-26T12:29:44.436921',
      metadata_modified: '2022-10-25T14:13:04.326489',
      mimetype: null,
      mimetype_inner: null,
      name: '00-SwissCamp10m',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 2,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 42123942,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/7ELDZR',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T14:58:59.050849',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: '6a8deaff-249d-4e21-b22f-466b41aa1dd1',
      last_modified: '2020-11-26T12:30:21.285585',
      metadata_modified: '2022-10-25T14:14:12.635085',
      mimetype: null,
      mimetype_inner: null,
      name: '01-SwissCamp',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 3,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 80269102,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/DZSKEM',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T15:02:24.007475',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: 'd4c584d0-bb89-4497-aded-1dd793f44bcf',
      last_modified: '2020-11-26T12:31:02.035280',
      metadata_modified: '2022-10-25T14:15:23.458341',
      mimetype: null,
      mimetype_inner: null,
      name: '02-CrawfordPoint1',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 4,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 61973379,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/IAHZYS',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T15:09:19.490699',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: 'e76d97ec-24a7-425e-89b9-8a64497456a3',
      last_modified: '2020-11-26T12:31:53.316613',
      metadata_modified: '2022-10-25T14:18:01.884580',
      mimetype: null,
      mimetype_inner: null,
      name: '03-NASA-U',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 5,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 86554893,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/XOMPZ0',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T15:15:16.353551',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: '180f906a-5fc8-4a7e-b9f7-ab00f7092d79',
      last_modified: '2020-12-02T08:17:26.583535',
      metadata_modified: '2022-10-25T14:19:29.030995',
      mimetype: null,
      mimetype_inner: null,
      name: '04-GITS',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 6,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 63894886,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/SJRCOC',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T15:20:57.011514',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: '43c16eb8-d83c-4b11-967a-e74d0a8c98a0',
      last_modified: '2020-11-26T12:33:11.110079',
      metadata_modified: '2022-10-25T14:20:15.885584',
      mimetype: null,
      mimetype_inner: null,
      name: '05-Humboldt',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 7,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 63987342,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/BUOC7Y',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T15:26:36.580817',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: '439f12e3-aa7a-438b-9ed6-7ebcf1593958',
      last_modified: '2020-12-02T08:36:09.058668',
      metadata_modified: '2022-10-25T14:23:29.922406',
      mimetype: null,
      mimetype_inner: null,
      name: '06-Summit',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 8,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 88354682,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/UFCSAS',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T15:33:15.251372',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: 'b1704ccb-d942-4648-96e6-6e785f25941a',
      last_modified: '2020-12-02T13:56:18.733916',
      metadata_modified: '2022-10-25T14:24:26.054063',
      mimetype: null,
      mimetype_inner: null,
      name: '07-Tunu-N',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 9,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 57976839,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/H2MOL7',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T15:37:02.206698',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: '1b31374b-53e4-48c8-9102-180833a624b2',
      last_modified: '2020-11-26T12:35:24.680839',
      metadata_modified: '2022-10-25T14:26:28.697427',
      mimetype: null,
      mimetype_inner: null,
      name: '08-DYE2',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 10,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 92384540,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/WAYCGA',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T15:40:47.301412',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: '4728afa8-b623-46e2-8368-9cdff4e26109',
      last_modified: '2020-11-26T12:36:09.663296',
      metadata_modified: '2022-10-25T14:28:26.523443',
      mimetype: null,
      mimetype_inner: null,
      name: '09-JAR1',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 11,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 113751799,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/9RJ9SC',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T15:44:13.485616',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: '7b154591-546b-44d0-864a-42ad27284f45',
      last_modified: '2020-11-26T12:36:57.958026',
      metadata_modified: '2022-10-25T14:29:02.334173',
      mimetype: null,
      mimetype_inner: null,
      name: '10-Saddle',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 12,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 85106917,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/MPAAGY',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T15:53:23.424697',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: 'ed272e01-d1aa-4a47-b773-000becafc844',
      last_modified: '2020-11-26T12:37:53.061777',
      metadata_modified: '2022-10-25T14:30:16.927059',
      mimetype: null,
      mimetype_inner: null,
      name: '11-SouthDome',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 13,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 105216949,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/4ONGVQ',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T15:56:54.756254',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: 'a18014f9-d763-4941-bad7-eb8dfceda6ba',
      last_modified: '2020-11-26T12:38:36.322293',
      metadata_modified: '2022-10-25T14:32:02.756582',
      mimetype: null,
      mimetype_inner: null,
      name: '12-NASA-E',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 14,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 73642934,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/FFJIRB',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T16:03:53.540042',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: 'fddbcb97-af37-4148-8803-a61796aa2482',
      last_modified: '2020-11-26T12:39:24.609270',
      metadata_modified: '2022-10-25T14:33:01.785618',
      mimetype: null,
      mimetype_inner: null,
      name: '15-NASA-SE',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 15,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 121694130,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/DD4FR3',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T16:18:11.082544',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: 'da43e101-9d48-4b05-ae96-5453c687b1ed',
      last_modified: '2020-11-26T12:40:02.477446',
      metadata_modified: '2022-10-25T14:35:43.978454',
      mimetype: null,
      mimetype_inner: null,
      name: '22-Petermann ELA',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 16,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 55732780,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/ZIOAIX',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T16:40:47.466314',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: '21ecc6db-bdb5-4bef-8bcb-4a3e92e9167f',
      last_modified: '2020-11-26T12:41:15.758188',
      metadata_modified: '2022-10-25T14:37:19.653157',
      mimetype: null,
      mimetype_inner: null,
      name: '23-NEEM',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 17,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 65661066,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/XQGUP7',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2020-11-03T16:37:37.245117',
      description: '',
      doi: '',
      format: 'NEAD',
      hash: '',
      id: 'd4691238-cd3f-457c-a59a-7f40f59bdf68',
      last_modified: '2020-11-26T12:40:38.325370',
      metadata_modified: '2022-10-25T14:36:38.199184',
      mimetype: null,
      mimetype_inner: null,
      name: '24-E-GRIP',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 18,
      publication_state: '',
      resource_size: '{"size_units": "kb", "size_value": ""}',
      resource_type: null,
      restricted:
        '{"allowed_users": "", "level": "public", "shared_secret": ""}',
      size: 26425867,
      state: 'active',
      url:
        'https://dataverse.geus.dk/api/access/datafile/:persistentId?persistentId=doi:10.22008/FK2/VVXGUT/B6HOFS',
      url_type: '',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2021-02-02T16:01:17.913120',
      description: '',
      doi: '',
      format: 'JSON',
      hash: '',
      id: 'deed64b5-e4ea-427e-98d6-45a6f0f26d96',
      last_modified: '2022-10-25T16:50:43.505644',
      metadata_modified: '2022-10-25T14:50:43.583082',
      mimetype: null,
      mimetype_inner: null,
      name: 'GC Net Config for Stations',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 19,
      publication_state: '',
      resource_size: '{"size_value": "", "size_units": "kb"}',
      resource_type: null,
      restricted:
        '{"level": "public", "allowed_users": "", "shared_secret": ""}',
      size: 101726,
      state: 'active',
      url:
        'https://www.envidat.ch/dataset/4be8caec-be03-4500-810b-3002c964d3b7/resource/deed64b5-e4ea-427e-98d6-45a6f0f26d96/download/stationsconfig.json',
      url_type: 'upload',
    },
    {
      cache_last_updated: null,
      cache_url: null,
      created: '2021-02-02T16:02:16.913041',
      description: '',
      doi: '',
      format: 'JSON',
      hash: '',
      id: 'f4a612b8-6bb0-4343-aecc-3656f70136eb',
      last_modified: null,
      metadata_modified: '2021-02-09T14:08:01.315879',
      mimetype: null,
      mimetype_inner: null,
      name: 'GC Net Chart Parameters',
      package_id: '4be8caec-be03-4500-810b-3002c964d3b7',
      position: 20,
      resource_size: '{"size_value": "", "size_units": "kb"}',
      resource_type: null,
      restricted:
        '{"level": "public", "allowed_users": "", "shared_secret": ""}',
      size: 7866,
      state: 'active',
      url:
        'https://www.envidat.ch/dataset/4be8caec-be03-4500-810b-3002c964d3b7/resource/f4a612b8-6bb0-4343-aecc-3656f70136eb/download/stationparameters.json',
      url_type: 'upload',
    },
  ],
  tags: [
    {
      display_name: 'AIR TEMPERATURE',
      id: 'ba9c8c16-f908-4173-affa-f813f7f8cd13',
      name: 'AIR TEMPERATURE',
      state: 'active',
      vocabulary_id: null,
    },
    {
      display_name: 'AUTOMATIC WEATHER STATION',
      id: 'b8416a96-5702-4af7-a731-8f19fdba8b4b',
      name: 'AUTOMATIC WEATHER STATION',
      state: 'active',
      vocabulary_id: null,
    },
    {
      display_name: 'AWS',
      id: 'c61bb0d0-9042-4a10-a74c-a3e66ddbd9ae',
      name: 'AWS',
      state: 'active',
      vocabulary_id: null,
    },
    {
      display_name: 'CLIMATE',
      id: '5a33b7dc-dca1-42c3-8651-9d00b5428823',
      name: 'CLIMATE',
      state: 'active',
      vocabulary_id: null,
    },
    {
      display_name: 'GREENLAND',
      id: '0e278d2c-562d-4427-941d-aba19d99f8d3',
      name: 'GREENLAND',
      state: 'active',
      vocabulary_id: null,
    },
    {
      display_name: 'NET RADIATION',
      id: 'e6bd526e-b7ac-4839-a69a-39ab7c7faa45',
      name: 'NET RADIATION',
      state: 'active',
      vocabulary_id: null,
    },
  ],
  groups: [],
  relationships_as_subject: [],
  relationships_as_object: [],
};
