export default {
  'wsl:29664': {
    object_url: 'https://www.dora.lib4ri.ch/wsl/islandora/object/wsl:29664',
    citation: {
      WSL: 'M\u00fcller S., Weber M., Buchecker M.  (2022). \u003Cspan style=\u0022font-style: normal;\u0022 \u003EWie soll die Energiestrategie 2050 lokal umgesetzt werden? Umfrage zur Energiewende und Mitwirkung bei der Umsetzung\u003C/span\u003E. WSL-Berichte: Vol. 117. Birmensdorf: Eidg. Forschungsanstalt f\u00fcr Wald, Schnee und Landschaft WSL. 71 p. ',
    },
    doi: '',
    abstract:
      'Obwohl die Mehrheit der Schweizer Bev\u00f6lkerung die Energiewende grunds\u00e4tzlich bef\u00fcrwortet, gestaltet sich die konkrete Umsetzung herausfordernd. Besonders bei der Windenergie sind ausgepr\u00e4gte Zielkonflikte erkennbar. Entsprechend sind geplante Windenergieprojekte h\u00e4ufig von Einsprachen betroffen oder werden zu einem sp\u00e4ten Zeitpunkt im Planungsverfahren von der Bev\u00f6lkerung bei einer Abstimmung abgelehnt. Ein h\u00e4ufig genanntes Argument gegen lokale Windenergieanlagen ist die Ver\u00e4nderung der Landschaft oder eine Verletzung der Bedeutung eines Ortes. Da Landschaften und Orte jedoch nicht einfach Gegenst\u00e4nde darstellen, sondern gesellschaftliche Verh\u00e4ltnisse repr\u00e4sentieren, ist es wichtig, die Gr\u00fcnde f\u00fcr die Reaktionen vertiefter und in ihrem Gesamtkontext zu betrachten. Dabei gilt es auch die Anspr\u00fcche der Bev\u00f6lkerung hinsichtlich prozeduraler Aspekte zu ber\u00fccksichtigen, um L\u00f6sungen f\u00fcr die Umsetzung der Energiewende auf lokaler Ebene zu finden, f\u00fcr die auch die Realisierung von Windenergieprojekten notwendig ist. [...]\u003Cbr /\u003E\u003Cbr /\u003EAlthough the majority of the Swiss population generally supports the energy transition, its local implementation has proven to be challenging. Especially regarding the planning process of wind power, conflicting interests regularly manifest themselves in legal objections or the project is rejected in a referendum at a later stage. A frequently cited argument against wind energy infrastructure is its impact on the landscape or the meaning of a place. Landscapes or places cannot be reduced to mere collection of objects but have to be conceived as representations of societal relationships. Therefore, it is necessary to understand the reasons for these reactions more fundamentally and in consideration of their specific context. In doing so, residents\u2019 expectations in terms of procedural aspects have to be considered, in order to identify solutions for implementing an energy transition at the local level. [...]',
  },
  'wsl:21835': {
    object_url: 'https://www.dora.lib4ri.ch/wsl/islandora/object/wsl:21835',
    citation: {
      WSL: 'Risch A.C., Zimmermann S., Ochoa-Hueso R., Sch\u00fctz M., Frey B., Firn J.L., \u2026 Moser B.  (2019). Soil net nitrogen mineralisation across global grasslands. Nat. Commun. \u003Cspan style=\u0022font-style: normal;\u0022 \u003E10\u003C/span\u003E(1), 4981 (10 pp.). \u003Ca href=\u0022https://doi.org/10.1038/s41467-019-12948-2\u0022 target=\u0022_blank\u0022\u003Ehttps://doi.org/10.1038/s41467-019-12948-2\u003C/a\u003E',
    },
    doi: '10.1038/s41467-019-12948-2',
    abstract:
      'Soil nitrogen mineralisation (N\u003Csub\u003Emin\u003C/sub\u003E), the conversion of organic into inorganic N, is important for productivity and nutrient cycling. The balance between mineralisation and immobilisation (net N\u003Csub\u003Emin\u003C/sub\u003E) varies with soil properties and climate. However, because most global-scale assessments of net N\u003Csub\u003Emin\u003C/sub\u003E are laboratory-based, its regulation under field-conditions and implications for real-world soil functioning remain uncertain. Here, we explore the drivers of realised (field) and potential (laboratory) soil net N\u003Csub\u003Emin\u003C/sub\u003E across 30 grasslands worldwide. We find that realised N\u003Csub\u003Emin\u003C/sub\u003E is largely explained by temperature of the wettest quarter, microbial biomass, clay content and bulk density. Potential N\u003Csub\u003Emin\u003C/sub\u003E only weakly correlates with realised N\u003Csub\u003Emin\u003C/sub\u003E, but contributes to explain realised net N\u003Csub\u003Emin\u003C/sub\u003E when combined with soil and climatic variables. We provide novel insights of global realised soil net N\u003Csub\u003Emin\u003C/sub\u003E and show that potential soil net N\u003Csub\u003Emin\u003C/sub\u003E data available in the literature could be parameterised with soil and climate data to better predict realised N\u003Csub\u003Emin\u003C/sub\u003E.',
  },
  'wsl:22390': {
    object_url: 'https://www.dora.lib4ri.ch/wsl/islandora/object/wsl:22390',
    citation: {
      WSL: 'Weber M., M\u00fcller S., Buchecker M.  (2020). Lokale Umsetzung der Energiewende\u00a0in der Schweiz. Befragung zur Einstellung in der Bev\u00f6lkerung und der Bereitschaft mitzuwirken. Nat.schutz Landsch.plan. \u003Cspan style=\u0022font-style: normal;\u0022 \u003E52\u003C/span\u003E(1), 16-23. ',
    },
    doi: '',
    abstract:
      'Die Bev\u00f6lkerung steht hinter der F\u00f6rderung erneuerbarer Energien. Geht es jedoch um die konkrete Umsetzung, sind Zielkonflikte erkennbar. Diverse Studien legen nahe, dass die Beteiligung der Bev\u00f6lkerung bei der Planung wichtig f\u00fcr die soziale Akzeptanz erneuerbarer Energieanlagen ist. Die Schweiz ist hierbei ein interessantes Beispiel, da durch die direkte Demokratie ein besonders ausgepr\u00e4gtes Mitspracherecht besteht und sich die lokale Umsetzung erneuerbarer Energieprojekte dennoch schwierig gestaltet.\u003Cbr /\u003E\nVor diesem Hintergrund wurde eine Bev\u00f6lkerungsumfrage in einer Region durchgef\u00fchrt, in der die Realisierung eines Windparks zur Debatte steht. Untersucht wurde die Einstellung der Bev\u00f6lkerung zur Energiewende und wie stark und auf welche Weise sie in die Planung miteinbezogen werden m\u00f6chte. Die Resultate zeigen, dass betr\u00e4chtliche Wissensdefizite dar\u00fcber bestehen, nach welchen Kriterien die Standorte erneuerbarer Energieanlagen ausgew\u00e4hlt werden. Auch ist erkennbar, dass sich die Bev\u00f6lkerung eine st\u00e4rkere Beteiligung w\u00fcnscht,\u00a0vor\u00a0allem bei der Wahl des Standorts und der erneuerbaren Energiequelle.\u003Cbr /\u003E\u003Cbr /\u003E\nThe Swiss population supports the promotion of renewable\u00a0energy sources. However, when it comes to specific implementation, conflicting goals can be identified. Various studies indicate that public participation during the planning stages is key for social acceptance of renewable energy plants. Due to its direct democratic institutions, Switzerland allows its citizens to have their voices heard when it comes to public spending, yet local implementation of renewable energy projects remains difficult. The present report uses a population survey in a region in which the development of a wind park is currently being debated. The object of investigation is the population\u2018s attitude towards transformation of the energy system and to what extent and how they would like to be involved in the planning process. The results of the survey suggest that there is a considerable lack of knowledge on how sites for renewable energy plants are selected. Accordingly, the local population wishes greater participation, especially when it comes to the selection of construction sites and energy sources.',
  },
  'wsl:32593': {
    object_url: 'https://www.dora.lib4ri.ch/wsl/islandora/object/wsl:32593',
    citation: {
      WSL: 'Ballikaya P., Song W., Bachmann O., Guillong M., Wang X., Cherubini P.  (2023). Chemical elements recorded by Q\u003Cem\u003Euercus mongolica\u003C/em\u003E Fisch. ex Ledeb. tree rings reveal trends of pollution history in Harbin, China. Forests \u003Cspan style=\u0022font-style: normal;\u0022 \u003E14\u003C/span\u003E(2), 187 (18 pp.). \u003Ca href=\u0022https://doi.org/10.3390/f14020187\u0022 target=\u0022_blank\u0022\u003Ehttps://doi.org/10.3390/f14020187\u003C/a\u003E',
    },
    doi: '10.3390/f14020187',
    abstract:
      'Rapid industrialization has led to a dramatic increase in air pollution. In China, the factors driving the abundance and composition of smog, particularly fine particulate matter, remain poorly understood, and short-term air pollution data are available from few air quality monitoring networks. Using laser ablation-inductively coupled plasma-mass spectrometry (LA-ICP-MS), chemical elements (Mg, Al, Si, S, K, Ca, Ti, Cr, Mn, Fe, Co, Ni, Cu, Zn, As, Sr, Tl, Pb, Bi) were analyzed in \u003Cem\u003EQuercus mongolica\u003C/em\u003E Fisch. ex Ledeb. tree rings from Harbin, China, in latewood at 5-year resolution over the period 1965-2020. The temporal trend of some elements was influenced by physiological factors, by environmental factors such as pollution, or influenced by both. Mg, K, Zn, Cu, Ni, Pb, As, Sr and Tl showed changes in pollution levels over time. The signal of K, Zn, Ni, Cu and Pb in trees from Harbin statistically did not differ from those at the control site after the 2000s. Our analysis confirmed the success of the undertaken emission reduction measures, which lead to an improvement in China\u2019s urban air quality after 2010. However, As increased from 2000 to 2020 in Harbin which is consistent with rising As concentrations in China. Our study proved that dendrochemistry is a reliable tool to monitor the long-term history of pollution and to contribute to extending instrumental records of pollution back in time.',
  },
};
