export default [
  {
    pid: 'wsl:23144',
    object_url: 'https://www.dora.lib4ri.ch/wsl/islandora/object/wsl:23144',
    citation: {
      WSL:
        'Neff F., Resch M.C., Marty A., Rolley J.D., Sch\u00fctz M., Risch A.C., Gossner M.M.  (2020). Long\u2010term restoration success of insect herbivore communities in semi\u2010natural grasslands: a functional approach. Ecol. Appl. \u003Cspan style=\u0022font-style: normal;\u0022 \u003E30\u003C/span\u003E(6), e02133 (12 pp.). \u003Ca href=\u0022https://doi.org/10.1002/eap.2133\u0022 target=\u0022_blank\u0022\u003Ehttps://doi.org/10.1002/eap.2133\u003C/a\u003E',
    },
    doi: '10.1002/eap.2133',
    abstract:
      'Semi\u2010natural grasslands are important biodiversity hotspots, but increasingly degraded by intensive agriculture. Grassland restoration is considered to be promising in halting the ongoing loss of biodiversity, but this evaluation is mostly based on plant\u2010communities. Insect herbivores contribute substantially to grassland biodiversity and to the provisioning of a variety of ecosystem functions. However, it is unclear how they respond to different measures, which are commonly used to restore semi\u2010natural grasslands from intensively used agricultural land. We studied the long\u2010term success of different restoration techniques, which were originally targeted at re\u2010establishing semi\u2010natural grassland plant communities, for herbivorous insect communities on taxonomic as well as functional level. Therefore, we sampled insect communities 22 years after the establishment of restoration measures. These measures ranged from harvest and removal of biomass to removal of the topsoil layer and subsequent seeding of plant propagules. We found that insect communities in restored grasslands had higher taxonomic and functional diversity compared to intensively managed agricultural grasslands and were more similar in composition to target grasslands. Restoration measures including topsoil removal proved to be more effective, in particular in restoring species characterized by functional traits susceptible to intensive agriculture (e.g., large\u2010bodied species). Our study shows that long\u2010term success in the restoration of herbivorous insect communities of semi\u2010natural grasslands can be achieved by different restoration measures and that more invasive approaches that involve the removal of the topsoil layer are more effective. We attribute these restoration successes to accompanying changes in the plant community, resulting in bottom\u2010up control of the herbivore community. Our results are of critical importance for management decisions aiming to restore multi\u2010trophic communities, their functional composition and consequently the proliferation of ecosystem functions.',
  },
];
